### ISSUE TITLE
migrate content from previous site

### ISSUE THREAD

**Issue by carueda** [mmisw/mmiorr-docs#4]
Migrate content from previous site https://marinemetadata.org/mmiorrusrman
minimally "as is" (to then proceed with any needed updates on the new space), but possibly doing adjustments opportunistically.

**Comment by graybeal** [comment]
This work is mostly done. 

I’ve been working on the ORR documentation, and made a fair bit of progress.  

All of the pages are updated for the version 3 ORR, with 4 exceptions: viewing vocabularies, updating vocabularies, creating a mapping ontology, and updating a mapping ontology.

The significant changes include:
* improved image formats (changed the CSS), 
* reorganized the entire content, in too many ways to mention.
* labeled every page to indicate its status. (If I had known I would finish all but 4 pages, I would have just labeled the outdated ones!)
* lots of new images.
* significant update to About page (http://mmisw.org/orrdoc/about/)
* rewrote the FAQ as needed for consistency and de-duplication (http://mmisw.org/orrdoc/faq/)
* referred to identifiers as IRIs throughout, well, almost.

What I haven’t done yet is do some current Camtasia recordings. But I think that isn’t critical to declaring the docs ready

**Comment by carueda** [comment]
Ok, let's close this one.
