### ISSUE TITLE
need better naming/branding conventions for ORR

### ISSUE THREAD

**Issue by graybeal** [mmisw/mmiorr-docs#8]
All of the pre-existing help documentation refers to MMI ORR as the item being described, and often points to the site at mmisw.org as the instance location.

Now we are trying to update this documentation so it applies to version 3, and to COR. This creates all sorts of confusion, as the references to the mmisw.org site will be wrong both technically (because it isn't version 3 yet) and from a deployment status (because it doesn't make clear the distinction between the COR deployment and the mmisw.org deployment, nor the distinction between the software (called "ORR" throughout) and the deployment (which could be mmisw.org or cor.esipfed.org now, but might extend to future deployments).

So we need language to refer to the core software 'brand', as it's evolving -- the thing that lives in github and goes through different versions. Then we need terms for the MMI deployment, and the COR deployment.

**Comment by graybeal** [comment]
just brainstorming here ... seems to me the software should be something like "MMI's semantic repository software". We can call it ORR, but then we need to _not_ call the mmisw.org deployment ORR, because users can't tell what we're talking about. 

I'd like to call cor.esipfed.org the ESIP COR deployment, or the COR deployment for short.

By analogy, that would make mmisw.org the MMI ORR deployment, or the MMI deployment for short. (Not the "ORR deployment", because often we'll say COR is "an ORR deployment", which is pretty confusing.)

In the documentation, it would be best to minimize reference to specific repositories. The specific repositories will change over time, and we don't want to have to update 100 references in the software. Let's create a single page that lists all the repositories, and refer to that page when we need to mention "the repositories", or "the MMI semantic repository deployments".

**Comment by fgayanilo** [comment]
I agree with the above but I think it will be best to name the 'engine' that drives the ESIP COR and MMI ORR, and simply document that 'engine' rather than the deployment themselves. We let deployments be documented as they (lead PIs?) see fit as part of their technology stacks. I do not have a name for it since the ORR is the first that jumps to my head; 'Core ORR' is the label I have to date.

**Comment by carueda** [comment]
Thank guys, yes, agree with what this issue entry is about. Precisely the goal of the update task here is, in good part, to "fix" the MMI ORR-focused documentation that has been just copied-pasted from marinemetadata.

A few points:  (some of them as reiteration of what you have already said)
- yes, we definitely need a name for the software itself, and use it consistently
- my working (rather implicit) assumption for such name for the last several months (years?) has been "ORR"
- this is reflected in the recent ESIP presentations
- but **not yet** in this documentation, which, as already said, is at this point still a blind cop-n-paste from the MMI ORR-focused documentation at marinemetadata
- in a generic way we could refer to particular deployments as "ORR instances" or "ORR deployments" 
- the simple "ORR" could of course be qualified, e.g., "ORR Engine", "ORR System", "ORR Core".
- But note that the ORR not only comprises a backend, but also a front-end; and both could in principle be deployed in separation. The point is, a name like "ORR Engine" or "ORR Core" for the whole system would be misleading (unless further contextualized).  "ORR System" (or even "ORR Software or "ORR Application") would be preferable.
- yes, the instance at mmisw can simply continue to be called the "MMI ORR."
- Just entered #9, which is of course relevant.

**Comment by graybeal** [comment]
OK, I needed to decide on something so I could go ahead. The documentation at http://mmisw.org/orrdoc/introduction/ has the final answer ("ORR"), which I think is consistent with both your comments. 

```
The ORR has several deployments. The first of these was the MMI ORR, 
and some older documentation uses this name to refer to the software system,
the deployed service, or both. (In this document we use "ORR", "ORR software", 
or "ORR system" to refer to the software, and specific names like "MMI ORR" or 
"COR" to refer to particular deployments.)

Another major deployment of the ORR system is for the ESIP Federation's 
Community Ontology Repository, shown below; this is known as the ESIP COR, 
or simply the COR.
```

**Comment by carueda** [comment]
Thanks!
